import { BrandMark } from '../components/BrandMark';
import type { TelegramUser, Theme } from '../types';
import { Icon } from '../components/Icon';
import { useAuth } from '../hooks/useAuth';
import { identityProviders } from '../auth/providers';
export function ProfilePage({ user, theme, setTheme, favoritesCount, openFavorites, city, openLogin, browserMode = false }: { browserMode?: boolean; user?: TelegramUser; theme: Theme; setTheme: (theme: Theme) => void; favoritesCount: number; openFavorites: () => void; city: string; openLogin: () => void }) {
 const { state, error, signOut } = useAuth();
 const profile = state.profile;
 const avatar = profile?.avatar_url ?? (state.status !== 'authenticated' && !browserMode ? user?.photo_url : undefined);
 const name = state.status === 'authenticated' ? profile?.display_name || 'Ваш профиль' : (browserMode ? 'Вы не вошли в аккаунт' : user ? `${user.first_name} ${user.last_name ?? ''}`.trim() : 'Привет, сосед!');
 return <><div className="page-heading"><span className="eyebrow">ТВОЁ ПРОСТРАНСТВО</span><h1>Профиль</h1></div>
 <section className="profile-card" aria-busy={state.status === 'loading'}><div className="avatar large-avatar"><Icon name="profile" size={32}/>{avatar && <img src={avatar} alt={profile ? 'Аватар профиля' : 'Аватар Telegram'} referrerPolicy="no-referrer" onError={e => { e.currentTarget.hidden = true; }}/>}</div><h2>{state.status === 'loading' ? 'Проверяем состояние входа…' : name}</h2><p>{state.status !== 'authenticated' && !browserMode && user?.username && !profile ? `@${user.username} · ` : ''}{profile?.city ?? city}</p>
 {state.status === 'authenticated' ? <>{!profile && <p>Профиль ещё загружается или готовится. Попробуйте обновить страницу позже.</p>}<span className="profile-badge">Аккаунт Рядом · {favoritesCount} в избранном</span><div className="linked-identities"><h3>Способы входа</h3>{state.identities.length ? <ul>{state.identities.map(identity => <li key={identity.id}>{identityProviders.find(provider => provider.id === identity.provider)?.label ?? identity.provider}<span>Привязан</span></li>)}</ul> : <p>Нет связанных способов входа</p>}</div><button className="account-signout" onClick={() => { void signOut(); }}>Выйти</button></> : browserMode ? <><p>Ваши находки и настройки на этом устройстве</p><button className="primary-button profile-login" onClick={openLogin}>Войти или зарегистрироваться <Icon name="arrow" size={18}/></button></> : <span className="profile-badge">{user ? 'Данные Telegram · вход в аккаунт ещё не подключён' : 'Гость · без регистрации'}</span>}
 {error && <p role="status">{error}</p>}</section>
 <button className="profile-row" onClick={openFavorites}><span className="row-icon"><Icon name="heart"/></span><span><strong>Избранное</strong><small>Все твои находки в одном месте</small></span><span className="row-count">{favoritesCount}</span><Icon name="arrow" size={19}/></button>
 <div className="profile-future">{['Мои отзывы', 'Мои организации', 'Мои события'].map(title => <button className="profile-row" key={title} disabled><span><strong>{title}</strong></span><span className="row-count">Скоро</span></button>)}</div>
 <section className="settings-card"><h2>Как тебе удобнее</h2><p>Тема приложения</p><div className="theme-options" role="group" aria-label="Тема приложения">{([{ value: 'system', label: 'Авто', icon: 'profile' }, { value: 'light', label: 'Светлая', icon: 'sun' }, { value: 'dark', label: 'Тёмная', icon: 'moon' }] as const).map(option => <button key={option.value} className={theme === option.value ? 'selected' : ''} aria-pressed={theme === option.value} onClick={() => setTheme(option.value)}><Icon name={option.icon} size={20}/>{option.label}</button>)}</div><small>{browserMode ? 'Авто — тема вашего устройства.' : 'Авто — тема Telegram, а в браузере — тема устройства.'}</small></section>
 <section className="about-card"><span className="brand about-brand">рядом<BrandMark/></span><h2>Город ближе, чем кажется.</h2><p>Открывай места, строй планы и находи своих людей. Всё хорошее может быть совсем рядом.</p><div className="demo-note">Рядом — городской гид. Места — реальные, данные предоставлены пользователем. Афиша и услуги пока содержат демонстрационные данные: организации, адреса, исполнители, рейтинги и предложения в этих разделах вымышлены. Даты событий отсчитываются от дня просмотра. Покупки и запись недоступны.</div><small>Версия 0.1.0 · Сделано для небольших городов</small></section><p className="privacy-note">{state.status === 'authenticated' ? 'Избранное синхронизируется с аккаунтом. Локальный кеш хранится отдельно для каждого аккаунта; тема сохраняется на устройстве.' : browserMode ? 'Избранное и тема хранятся только в этом браузере и не синхронизируются между устройствами.' : 'Избранное и тема хранятся только в этом браузере. Данные Telegram используются для отображения профиля, не отправляются на сервер и не являются проверенной авторизацией.'}</p></>;
}
